# Generated by Django 6.0.1 on 2026-05-18 14:47

from django.db import migrations, models


def populate_price_lists(apps, schema_editor):
    OrganizationSettings = apps.get_model('accounts', 'OrganizationSettings')
    for settings_row in OrganizationSettings.objects.all():
        label = (settings_row.price_list_label or '2026/1. LİSTE').strip() or '2026/1. LİSTE'
        settings_row.price_lists = [
            {'key': 'list_1', 'label': label, 'is_default': True},
            {'key': 'list_2', 'label': '2026/2. LİSTE', 'is_default': False},
        ]
        settings_row.save(update_fields=['price_lists'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organizationsettings_price_list_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='price_lists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_price_lists, migrations.RunPython.noop),
    ]
