# Generated by Codex on 2026-05-18

from django.db import migrations, models


DEFAULT_PAYMENT_OPTIONS = [
    '%100 Nakit',
    '%50 peşin / %50 teslimde',
    '%30 peşin / %70 sevkiyat öncesi',
    '%20 nakit / %80 çek 90 gün',
    'Kredi kartı tek çekim',
    'Kredi kartı 3 taksit',
    'Kredi kartı 6 taksit',
    'Barter',
]


def populate_payment_options(apps, schema_editor):
    OrganizationSettings = apps.get_model('accounts', 'OrganizationSettings')
    for settings_row in OrganizationSettings.objects.all():
        settings_row.payment_options = list(DEFAULT_PAYMENT_OPTIONS)
        settings_row.save(update_fields=['payment_options'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_organizationsettings_price_lists_alter_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='payment_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_payment_options, migrations.RunPython.noop),
    ]
