# Generated by Django 6.0.1 on 2026-05-25 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_organizationsettings_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Usta başı / ekip lideri — görev ekibe düşünce önce bu kişiye atanır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
