# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='service_expense_tax_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
