# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contract_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='numberrange',
            name='doc_type',
            field=models.CharField(
                choices=[
                    ('QUOTE', 'Quote'),
                    ('CONTRACT', 'Contract'),
                    ('ORDER', 'SalesOrder'),
                    ('INVOICE', 'Invoice'),
                ],
                max_length=20,
            ),
        ),
    ]
