# Generated by Django 6.0.1 on 2026-05-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_contract_settings_and_contract_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
