# Generated by Django 6.0.1 on 2026-06-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_id', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('vendor', models.CharField(blank=True, default='', max_length=120)),
                ('version', models.CharField(blank=True, default='', max_length=40)),
                ('version_id', models.PositiveIntegerField(default=0)),
                ('min_core_version', models.CharField(blank=True, default='', max_length=40)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('is_installed', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['addon_id'],
            },
        ),
        migrations.CreateModel(
            name='AddonEventListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=160)),
                ('handler', models.CharField(max_length=300)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_listeners', to='addons.addon')),
            ],
            options={
                'ordering': ['event', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AddonInstallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_addon_id', models.CharField(blank=True, default='', max_length=120)),
                ('action', models.CharField(choices=[('discover', 'Discover'), ('install', 'Install'), ('enable', 'Enable'), ('disable', 'Disable'), ('upgrade', 'Upgrade'), ('uninstall', 'Uninstall'), ('rebuild', 'Rebuild'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='addons.addon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AddonVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('version_id', models.PositiveIntegerField(default=0)),
                ('manifest_hash', models.CharField(blank=True, default='', max_length=128)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='addons.addon')),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='AddonAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('asset_type', models.CharField(max_length=60)),
                ('path', models.CharField(max_length=500)),
                ('integrity_hash', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='addons.addon')),
            ],
            options={
                'unique_together': {('addon', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AddonDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=80)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to='addons.addon')),
            ],
            options={
                'unique_together': {('addon', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='AddonNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('label', models.CharField(max_length=180)),
                ('parent_key', models.CharField(blank=True, default='', max_length=160)),
                ('route', models.CharField(blank=True, default='', max_length=260)),
                ('icon', models.CharField(blank=True, default='FolderKanban', max_length=80)),
                ('required_permission', models.CharField(blank=True, default='', max_length=120)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation', to='addons.addon')),
            ],
            options={
                'ordering': ['display_order', 'label'],
                'unique_together': {('addon', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AddonOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('option_type', models.CharField(blank=True, default='text', max_length=40)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='addons.addon')),
            ],
            options={
                'ordering': ['display_order', 'key'],
                'unique_together': {('addon', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AddonRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], max_length=20)),
                ('key', models.CharField(max_length=160)),
                ('path', models.CharField(max_length=260)),
                ('binding', models.CharField(blank=True, default='', max_length=300)),
                ('required_permission', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='addons.addon')),
            ],
            options={
                'ordering': ['path', 'key'],
                'unique_together': {('addon', 'kind', 'key')},
            },
        ),
    ]
