# Generated by Django 6.0.1 on 2026-06-03 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('fallback_language_id', models.CharField(blank=True, default='', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AddonCompiledTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('content', models.TextField(blank=True, default='')),
                ('applied_modifications', models.JSONField(blank=True, default=list)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('rebuilt_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'title'],
                'unique_together': {('template_type', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AddonPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.CharField(default='tr-TR', max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField(blank=True, default='')),
                ('version_id', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='addons.addon')),
            ],
            options={
                'ordering': ['language_id', 'title'],
                'unique_together': {('language_id', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AddonStyleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180)),
                ('asset_type', models.CharField(default='less', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_assets', to='addons.addon')),
            ],
            options={
                'ordering': ['display_order', 'key'],
                'unique_together': {('addon', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AddonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('admin', 'Admin'), ('public', 'Public'), ('email', 'Email'), ('document', 'Document'), ('frontend', 'Frontend')], default='frontend', max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('content', models.TextField(blank=True, default='')),
                ('version_id', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='addons.addon')),
            ],
            options={
                'ordering': ['template_type', 'title'],
                'unique_together': {('template_type', 'title')},
            },
        ),
        migrations.CreateModel(
            name='AddonTemplateModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(default='frontend', max_length=30)),
                ('template', models.CharField(max_length=220)),
                ('modification_key', models.CharField(max_length=220)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('str_replace', 'String replace'), ('preg_replace', 'Regex replace'), ('append', 'Append'), ('prepend', 'Prepend')], default='str_replace', max_length=40)),
                ('find', models.TextField(blank=True, default='')),
                ('replace', models.TextField(blank=True, default='')),
                ('execution_order', models.IntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_modifications', to='addons.addon')),
            ],
            options={
                'ordering': ['template_type', 'template', 'execution_order', 'modification_key'],
                'unique_together': {('addon', 'modification_key')},
            },
        ),
    ]
