# Generated by Django 6.0.1 on 2026-06-04 14:09

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_NAVIGATION_ITEMS = [
    ("dashboard", "Kontrol Paneli", "", "/", "Home", "settings.view", 10, {}),
    ("task_history", "Geçmiş görevler", "", "/task-history", "CalendarClock", "tasks.view.own", 30, {}),
    ("change_password", "Şifre değiştir", "", "/change-password", "KeyRound", "", 40, {}),
    ("crm", "CRM", "", "", "Gauge", "", 100, {}),
    ("partners", "Cari Kartı", "crm", "/crm/companies", "Building2", "partners.view", 120, {}),
    ("quotes", "Teklif & Sözleşmeler", "crm", "/crm/quotes", "FileText", "quotes.view.own", 140, {}),
    ("quote_templates", "Şablon Yönetimi", "crm", "/crm/quote-templates", "Settings2", "templates.view", 160, {}),
    ("erp", "ERP", "", "", "Package", "erp.view", 200, {}),
    ("inventory", "Stok", "erp", "/erp/inventory", "Package", "inventory.view", 230, {}),
    ("warehouse_management", "Depo Yönetimi", "erp", "/erp/warehouse-management", "Package", "warehouses.manage", 240, {}),
    ("warehouse", "Depo", "erp", "/erp/warehouse", "Package", "warehouse_stock.view", 250, {}),
    ("production", "İmalat Yönetimi", "erp", "/erp/production", "Settings2", "production.view", 260, {}),
    ("production_orders", "İş Emirleri", "erp", "/erp/production/orders", "FileText", "production.work_orders.view", 270, {}),
    ("production_console", "İstasyon Konsolu", "erp", "/erp/production/console", "Monitor", "production.station.operate", 280, {}),
    ("production_reports", "İmalat Raporları", "erp", "/erp/production/reports", "BarChart3", "production.reports.view", 290, {}),
    ("support", "Destek", "", "", "Activity", "", 400, {}),
    ("tickets", "Destek talepleri", "support", "/support/tickets", "Activity", "tickets.view", 410, {}),
    ("settings", "Ayarlar", "", "/settings", "Settings", "settings.view", 540, {}),
]


def seed_default_navigation(apps, schema_editor):
    NavigationItem = apps.get_model("addons", "NavigationItem")
    for key, label, parent, route, icon, permission, order, meta in DEFAULT_NAVIGATION_ITEMS:
        NavigationItem.objects.update_or_create(
            organization=None,
            key=key,
            defaults={
                "label": label,
                "parent_key": parent,
                "route": route,
                "icon": icon,
                "required_permission": permission,
                "display_order": order,
                "is_active": True,
                "is_system": True,
                "meta": meta,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_addonlanguage_addon_is_system_addoncompiledtemplate_and_more'),
        ('organizations', '0005_warehouse_operational_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('label', models.CharField(max_length=180)),
                ('parent_key', models.CharField(blank=True, default='', max_length=160)),
                ('route', models.CharField(blank=True, default='', max_length=260)),
                ('icon', models.CharField(blank=True, default='FolderKanban', max_length=80)),
                ('required_permission', models.CharField(blank=True, default='', max_length=120)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='organizations.organization')),
            ],
            options={
                'ordering': ['display_order', 'label'],
                'unique_together': {('organization', 'key')},
            },
        ),
        migrations.RunPython(seed_default_navigation, migrations.RunPython.noop),
    ]
