# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_salesorder_production_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='template_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
