# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_category_product_template_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attribute_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_schema_override',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
