# Generated by Django 6.0.1 on 2026-05-18 14:47

from django.db import migrations, models


def populate_product_price_lists(apps, schema_editor):
    Product = apps.get_model('erp', 'Product')
    for product in Product.objects.all():
        price = str(product.price or 0)
        product.price_lists = {'list_1': price, 'list_2': price}
        product.save(update_fields=['price_lists'])


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_category_attribute_schema_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_lists',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(populate_product_price_lists, migrations.RunPython.noop),
    ]
