# Generated by Django 6.0.1 on 2026-05-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_add_order_to_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='reserved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='location_from',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='location_to',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='erp.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
