# Generated by Django 6.0.1 on 2026-06-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_warehouse_inventory'),
        ('organizations', '0005_warehouse_operational_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='detail_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='detail_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('organization', 'location', 'product', 'detail_1_override', 'detail_2_override')},
        ),
    ]
