# Generated by Django 6.0.1 on 2026-06-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_product_technical_drawings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producttechnicaldrawing',
            new_name='erp_product_organiz_921d8a_idx',
            old_name='erp_product_organiz_80f20e_idx',
        ),
        migrations.RenameIndex(
            model_name='producttechnicaldrawing',
            new_name='erp_product_organiz_b63bd0_idx',
            old_name='erp_product_organiz_f7e73d_idx',
        ),
        migrations.AlterField(
            model_name='producttechnicaldrawing',
            name='file_type',
            field=models.CharField(choices=[('image', 'Gorsel')], default='download', max_length=20),
        ),
    ]
