# Generated by Codex on 2026-04-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teamassociate'),
        ('crm', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='authorized_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='tax_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='tax_office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='contract_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='document_type',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Contract', 'Contract')], default='Quote', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_quotes', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='quote',
            name='seller_company_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='section_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
