# Generated by Django 6.0.1 on 2026-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_businesspartner_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='price_list_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
