# Generated by Django 6.0.1 on 2026-05-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_quote_options_businesspartner_price_list_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
