PERMISSIONS_BY_MODULE = {
    "quotes": ["quotes.view", "quotes.edit", "quotes.prepare", "quotes.approve"],
    "pricing": ["pricing.manage"],
    "opportunities": ["opportunities.view", "opportunities.edit"],
    "contacts": ["contacts.view", "contacts.edit"],
    "invoices": ["invoices.view", "invoices.edit", "invoices.pay"],
    "products": ["products.view", "products.edit"],
    "partners": ["partners.view", "partners.edit"],
    "approvals": ["approvals.view"],
    "orders": ["orders.view", "orders.edit", "orders.receive"],
    "tickets": ["tickets.view", "tickets.edit"],
    "inventory": ["inventory.view", "inventory.edit"],
    "logistics": ["logistics.view", "logistics.edit"],
    "teams": ["teams.view", "teams.edit"],
    "tasks": ["tasks.view", "tasks.edit"],
    "vehicles": ["vehicles.view", "vehicles.edit"],
    "audit": ["audit.view"],
}

DEFAULT_ROLE_PERMS = {
    "Admin": sum(PERMISSIONS_BY_MODULE.values(), []),
    "Manager": [
        "quotes.view",
        "quotes.edit",
        "quotes.prepare",
        "quotes.approve",
        "pricing.manage",
        "opportunities.view",
        "opportunities.edit",
        "contacts.view",
        "contacts.edit",
        "invoices.view",
        "invoices.edit",
        "products.view",
        "products.edit",
        "partners.view",
        "partners.edit",
        "orders.view",
        "orders.edit",
        "orders.receive",
        "tickets.view",
        "tickets.edit",
        "inventory.view",
        "inventory.edit",
        "logistics.view",
        "logistics.edit",
        "approvals.view",
        "audit.view",
        "teams.view",
        "teams.edit",
        "tasks.view",
        "tasks.edit",
        "vehicles.view",
        "vehicles.edit",
    ],
    "Sales": [
        "quotes.view",
        "quotes.edit",
        "quotes.prepare",
        "products.view",
        "partners.view",
        "partners.edit",
        "contacts.view",
        "contacts.edit",
        "opportunities.view",
        "opportunities.edit",
        "orders.view",
        "tasks.view",
        "tasks.edit",
    ],
    "Finance": [
        "quotes.view",
        "quotes.approve",
        "invoices.view",
        "invoices.edit",
        "invoices.pay",
        "approvals.view",
        "audit.view",
        "orders.view",
    ],
    "Support": ["tickets.view", "tickets.edit", "tasks.view", "tasks.edit", "teams.view"],
    "Warehouse": ["products.view", "orders.view", "orders.receive", "inventory.view", "inventory.edit", "logistics.view", "logistics.edit", "tasks.view", "tasks.edit", "teams.view"],
    # Worker: saha/operasyon kullanıcıları için genişletilmiş salt-okuma + görev düzenleme + devir (görev atama YOK)
    "Worker": [
        "tasks.view",
        "tasks.edit",
        "tasks.handover",
        "products.view",
        "partners.view",
        "contacts.view",
        "opportunities.view",
        "tickets.view",
        "vehicles.view",
        "teams.view",
        "quotes.view",
    ],
}
