# Generated by Django 6.0.1 on 2026-05-25 17:59

import django.db.models.deletion
import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_team_leader'),
        ('support', '0030_repair_taskworkflowtemplate_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='action',
            field=models.CharField(choices=[('add_comment', 'Add comment'), ('set_assignee', 'Set assignee'), ('notify', 'Notify'), ('multi_notify', 'Notify multiple'), ('add_tag', 'Add tag'), ('set_field', 'Set field')], max_length=50),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('task_status_changed', 'Task status changed'), ('task_due_soon', 'Task due soon'), ('task_created', 'Task created')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to=support.models.task_attachment_path),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='workflow_team',
            field=models.ForeignKey(blank=True, help_text='Doluysa madde iş akışı bu ekibin adımına bağlıdır; sıra ve tik workflow ile senkron olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_checklist_items', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='taskproductionentry',
            name='product_line_index',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Çoklu ürün: 0-tabanlı kalem indeksi (yoksa eski/tek kalem davranışı)', null=True),
        ),
    ]
