import django.db.models.deletion
import production.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_warehouse_operational_fields'),
        ('erp', '0014_stockmovement_detail_1_stockmovement_detail_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_departments', to='organizations.organization')),
            ],
            options={'ordering': ['order', 'id'], 'unique_together': {('organization', 'code')}},
        ),
        migrations.CreateModel(
            name='ProductionRouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('product_group_key', models.CharField(blank=True, default='', max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_route_templates', to='organizations.organization')),
            ],
            options={'ordering': ['-is_default', 'name', 'id'], 'unique_together': {('organization', 'name')}},
        ),
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_stock_in_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_completion_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_completion_settings', to='erp.inventorylocation')),
                ('default_completion_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_completion_settings', to='organizations.warehouse')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_settings', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('max_workers', models.PositiveIntegerField(default=2)),
                ('is_handover', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='production.productiondepartment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_stations', to='organizations.organization')),
            ],
            options={'ordering': ['department__order', 'order', 'id'], 'unique_together': {('organization', 'code')}},
        ),
        migrations.CreateModel(
            name='ProductionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_devices', to='organizations.organization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='production.productionstation')),
            ],
            options={'ordering': ['station__code', 'name']},
        ),
        migrations.CreateModel(
            name='ProductionRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionroutetemplate')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_steps', to='production.productionstation')),
            ],
            options={'ordering': ['order', 'id'], 'unique_together': {('route', 'station')}},
        ),
        migrations.CreateModel(
            name='ProductionWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('source_type', models.CharField(blank=True, default='manual', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=120)),
                ('source_number', models.CharField(blank=True, default='', max_length=120)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('waiting', 'Bekliyor'), ('in_progress', 'Uretimde'), ('completed', 'Tamamlandi'), ('cancelled', 'Iptal')], default='waiting', max_length=20)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_work_orders', to='organizations.organization')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='production.productionroutetemplate')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='ProductionWorkOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(blank=True, default='', max_length=120)),
                ('product_name', models.CharField(max_length=255)),
                ('detail_1', models.CharField(blank=True, default='', max_length=500)),
                ('detail_2', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('technical_notes', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('stock_in_done', models.BooleanField(default=False)),
                ('stock_in_movement_id', models.BigIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lines', to='erp.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productionworkorder')),
            ],
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='ProductionStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('target_quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('locked', 'Kilitli'), ('ready', 'Hazir'), ('in_progress', 'Islemde'), ('waiting_handover', 'Devir bekliyor'), ('completed', 'Tamamlandi'), ('skipped', 'Atlandi')], default='locked', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_production_steps', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionworkorderline')),
                ('route_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_rows', to='production.productionroutestep')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_rows', to='production.productionstation')),
            ],
            options={'ordering': ['order', 'id'], 'unique_together': {('line', 'route_step')}},
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Baslat'), ('pause', 'Mola'), ('resume', 'Devam'), ('quantity', 'Adet girisi'), ('handover', 'Devret'), ('complete', 'Tamamla'), ('adjust', 'Duzeltme'), ('cancel', 'Iptal')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('counter_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=160)),
                ('source', models.CharField(blank=True, default='ui', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='production.productiondevice')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.productionworkorderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_events', to='organizations.organization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='production.productionstation')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.productionstepprogress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.productionworkorder')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='ProductionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=production.models.production_document_path)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='production.productionworkorderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_documents', to='organizations.organization')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='production.productionstation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='production.productionworkorder')),
            ],
            options={'ordering': ['-uploaded_at', '-id']},
        ),
        migrations.AddConstraint(
            model_name='productionevent',
            constraint=models.UniqueConstraint(condition=~models.Q(idempotency_key=''), fields=('organization', 'idempotency_key'), name='unique_production_event_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='productionworkorder',
            constraint=models.UniqueConstraint(condition=~models.Q(source_id=''), fields=('organization', 'source_type', 'source_id'), name='unique_production_work_order_source'),
        ),
    ]
