# Generated by Django 6.0.1 on 2026-06-03 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_warehouse_operational_fields'),
        ('production', '0003_deactivate_legacy_specific_preset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstepprogress',
            name='machine_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='ProductionWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Basladi'), ('paused', 'Molada'), ('handover', 'Devredildi'), ('closed', 'Kapandi')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_counter', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('end_counter', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('machine_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('declared_good_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discrepancy_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discrepancy_status', models.CharField(choices=[('none', 'Fark yok'), ('needs_review', 'Inceleme gerekli'), ('approved', 'Onaylandi'), ('corrected', 'Duzeltildi')], default='none', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='production.productionworkorderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_work_sessions', to='organizations.organization')),
                ('previous_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_sessions', to='production.productionworksession')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_production_work_sessions', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='production.productionstation')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='production.productionstepprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_work_sessions', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='production.productionworkorder')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='productionevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='production.productionworksession'),
        ),
        migrations.AddIndex(
            model_name='productionworksession',
            index=models.Index(fields=['organization', 'status'], name='production__organiz_169abd_idx'),
        ),
        migrations.AddIndex(
            model_name='productionworksession',
            index=models.Index(fields=['line', 'station', 'status'], name='production__line_id_e38bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='productionworksession',
            index=models.Index(fields=['user', 'started_at'], name='production__user_id_15ef24_idx'),
        ),
    ]
