# Generated by Django 6.0.1 on 2026-06-03 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_warehouse_operational_fields'),
        ('production', '0005_station_tablets_alerts_and_breaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionroutestep',
            name='start_policy',
            field=models.CharField(choices=[('after_previous', 'Onceki istasyondan sonra'), ('parallel', 'Paralel baslayabilir')], default='after_previous', max_length=24),
        ),
        migrations.CreateModel(
            name='ProductionStepTabletAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_step_tablet_assignments', to='organizations.organization')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_assignments', to='production.productionstepprogress')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_assignments', to='production.productionstationtablet')),
            ],
            options={
                'ordering': ['-is_pinned', 'priority', 'id'],
                'indexes': [models.Index(fields=['organization', 'tablet'], name='production__organiz_2acf16_idx'), models.Index(fields=['step', 'is_pinned', 'priority'], name='production__step_id_eca219_idx')],
                'unique_together': {('step', 'tablet')},
            },
        ),
    ]
