# Generated by Django 6.0.1 on 2026-06-03 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_warehouse_operational_fields'),
        ('production', '0006_productionroutestep_start_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCountingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Acik'), ('closed', 'Kapandi'), ('cancelled', 'Iptal')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('start_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('close_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('official_delta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('machine_delta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('close_reason', models.CharField(blank=True, choices=[('login', 'Yeni kisi girisi'), ('break_start', 'Mola baslangici'), ('break_end', 'Mola donusu'), ('logout', 'Cikis'), ('work_complete', 'Is emri tamamlandi'), ('manual', 'Manuel checkpoint')], default='', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counting_windows', to='production.productionworkorderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_counting_windows', to='organizations.organization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counting_windows', to='production.productionstation')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counting_windows', to='production.productionstepprogress')),
                ('tablet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counting_windows', to='production.productionstationtablet')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counting_windows', to='production.productionworkorder')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCountingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('declared_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credited_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discrepancy_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discrepancy_status', models.CharField(choices=[('none', 'Fark yok'), ('needs_review', 'Inceleme gerekli'), ('approved', 'Onaylandi'), ('corrected', 'Duzeltildi')], default='none', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_counting_participants', to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counting_participations', to='production.productionworksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_counting_participations', to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='production.productioncountingwindow')),
            ],
            options={
                'ordering': ['window_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('target_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_station_targets', to='organizations.organization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='production.productionstation')),
            ],
            options={
                'ordering': ['-target_date', 'station__code'],
            },
        ),
        migrations.AddIndex(
            model_name='productioncountingwindow',
            index=models.Index(fields=['organization', 'status'], name='production__organiz_a18ded_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncountingwindow',
            index=models.Index(fields=['station', 'status'], name='production__station_1c0a90_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncountingwindow',
            index=models.Index(fields=['tablet', 'status'], name='production__tablet__5c7ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncountingwindow',
            index=models.Index(fields=['opened_at'], name='production__opened__c33aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncountingparticipant',
            index=models.Index(fields=['organization', 'user'], name='production__organiz_77fc82_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncountingparticipant',
            index=models.Index(fields=['user', 'created_at'], name='production__user_id_2e8b1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productioncountingparticipant',
            unique_together={('window', 'session')},
        ),
        migrations.AddIndex(
            model_name='productionstationtarget',
            index=models.Index(fields=['organization', 'target_date'], name='production__organiz_a88df4_idx'),
        ),
        migrations.AddIndex(
            model_name='productionstationtarget',
            index=models.Index(fields=['station', 'target_date'], name='production__station_4e0130_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionstationtarget',
            unique_together={('organization', 'station', 'target_date')},
        ),
    ]
