# Generated by Django 6.0.1 on 2026-06-03 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_productioncountingwindow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncountingwindow',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counting_windows', to='production.productionworkorderline'),
        ),
        migrations.AlterField(
            model_name='productioncountingwindow',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counting_windows', to='production.productionstepprogress'),
        ),
        migrations.AlterField(
            model_name='productioncountingwindow',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counting_windows', to='production.productionworkorder'),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.productionworkorderline'),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.productionstepprogress'),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='production.productionworkorder'),
        ),
        migrations.AlterField(
            model_name='productionworksession',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='production.productionworkorderline'),
        ),
        migrations.AlterField(
            model_name='productionworksession',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='production.productionstepprogress'),
        ),
        migrations.AlterField(
            model_name='productionworksession',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='production.productionworkorder'),
        ),
    ]
