# Generated by Django 6.0.1 on 2026-06-04 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_technical_drawing_permissions'),
        ('production', '0009_shift_schedules_and_locks'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondepartment',
            name='notification_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_departments', to='accounts.usergroup'),
        ),
        migrations.AddField(
            model_name='productionstationalert',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_station_alerts', to='accounts.usergroup'),
        ),
    ]
