# Generated by Django 6.0.1 on 2026-06-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_production_report_templates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productionreporttemplate',
            new_name='production__organiz_d0c291_idx',
            old_name='production__organiz_996969_idx',
        ),
        migrations.RenameIndex(
            model_name='productionreporttemplate',
            new_name='production__organiz_6616e6_idx',
            old_name='production__organiz_416b18_idx',
        ),
    ]
