# Generated by Django 6.0.1 on 2026-06-07 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_rename_erp_product_organiz_80f20e_idx_erp_product_organiz_921d8a_idx_and_more'),
        ('organizations', '0005_warehouse_operational_fields'),
        ('production', '0013_station_default_daily_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v1', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinda'), ('archived', 'Arsiv')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_recipes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipes', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='erp.product')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_product_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product__sku', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecipeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, default='Adet', max_length=40)),
                ('quantity_type', models.CharField(choices=[('fixed', 'Sabit'), ('formula', 'Formul')], default='fixed', max_length=20)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('formula', models.CharField(blank=True, default='', max_length=500)),
                ('scrap_percent', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('detail_1_override', models.CharField(blank=True, default='', max_length=500)),
                ('detail_2_override', models.CharField(blank=True, default='', max_length=500)),
                ('consumption_timing', models.CharField(choices=[('station_close', 'Istasyon kapanisinda')], default='station_close', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_material_defaults', to='erp.inventorylocation')),
                ('material_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='erp.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipe_materials', to='organizations.organization')),
            ],
            options={
                'ordering': ['operation__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_version', models.CharField(blank=True, default='', max_length=50)),
                ('material_sku', models.CharField(max_length=120)),
                ('material_name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='Adet', max_length=40)),
                ('quantity_type', models.CharField(default='fixed', max_length=20)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('formula', models.CharField(blank=True, default='', max_length=500)),
                ('scrap_percent', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('planned_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('consumed_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('detail_1_override', models.CharField(blank=True, default='', max_length=500)),
                ('detail_2_override', models.CharField(blank=True, default='', max_length=500)),
                ('conditions_snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_requirements', to='erp.inventorylocation')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='production.productionworkorderline')),
                ('material_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_requirements', to='erp.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_material_requirements', to='organizations.organization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requirements', to='production.productionstation')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='production.productionstepprogress')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='production.productionworkorder')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_requirements', to='production.productrecipe')),
                ('recipe_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_requirements', to='production.productrecipematerial')),
            ],
            options={
                'ordering': ['station__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecipeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipe_operations', to='organizations.organization')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.productrecipe')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_operations', to='production.productionstation')),
            ],
            options={
                'ordering': ['recipe', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productrecipematerial',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.productrecipeoperation'),
        ),
        migrations.CreateModel(
            name='ProductionMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('produced_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('stock_movement_id', models.BigIntegerField(blank=True, null=True)),
                ('source_key', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionworkorderline')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_consumptions', to='erp.inventorylocation')),
                ('material_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_consumptions', to='erp.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_material_consumptions', to='organizations.organization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='production.productionstation')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionstepprogress')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='production.productioncountingwindow')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionworkorder')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='production.productionmaterialrequirement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'work_order'], name='production__organiz_7a077a_idx'), models.Index(fields=['station', 'created_at'], name='production__station_ed32fe_idx')],
                'unique_together': {('organization', 'requirement', 'source_key')},
            },
        ),
        migrations.AddIndex(
            model_name='productrecipe',
            index=models.Index(fields=['organization', 'product', 'status'], name='production__organiz_356a92_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecipe',
            index=models.Index(fields=['organization', 'status'], name='production__organiz_0e2137_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecipe',
            unique_together={('organization', 'product', 'version')},
        ),
        migrations.AddIndex(
            model_name='productionmaterialrequirement',
            index=models.Index(fields=['organization', 'work_order'], name='production__organiz_289445_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmaterialrequirement',
            index=models.Index(fields=['line', 'station'], name='production__line_id_1ece74_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmaterialrequirement',
            index=models.Index(fields=['material_product'], name='production__materia_2eb73d_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecipeoperation',
            index=models.Index(fields=['organization', 'recipe', 'order'], name='production__organiz_89d0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecipeoperation',
            index=models.Index(fields=['station'], name='production__station_76a949_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecipeoperation',
            unique_together={('recipe', 'station')},
        ),
        migrations.AddIndex(
            model_name='productrecipematerial',
            index=models.Index(fields=['organization', 'operation', 'is_active'], name='production__organiz_cfd7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='productrecipematerial',
            index=models.Index(fields=['material_product'], name='production__materia_96ec0d_idx'),
        ),
    ]
