# Generated by Django 6.0.1 on 2026-05-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_accesslog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='audit_acces_organiz_bc0634_idx',
            old_name='audit_acce_organiza_1163de_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='audit_acces_created_afc51a_idx',
            old_name='audit_acce_created__8c3f97_idx',
        ),
    ]
